# Generated by Django 6.0.7 on 2026-07-17 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("capacity", models.PositiveIntegerField()),
                ("event_date", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("uuid",), name="reservation_event_uuid_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=31,
                    ),
                ),
                ("tracking_id", models.UUIDField()),
                ("expired_at", models.DateTimeField(null=True)),
                ("confirmed_at", models.DateTimeField(null=True)),
                ("cancelled_at", models.DateTimeField(null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservation.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "confirmed"])),
                        fields=("event", "user"),
                        name="unique_reservation_per_user_event",
                    ),
                    models.UniqueConstraint(
                        fields=("tracking_id",), name="unique_tracking_id"
                    ),
                ],
            },
        ),
    ]
